accelerator: cpu
alias: null
batch_size: 32
drop_last_loader: false
early_stop_patience_steps: -1
futr_exog_list:
- dayofweek
- holiday_length
- holiday_continue
- road_build
- road_block_count
- total_block_count
- "holiday_name_\u8DE8\u5E74\u5143\u65E6"
- "holiday_name_\u4E8C\u4E8C\u516B\u7D00\u5FF5\u65E5"
- "holiday_name_\u6BCD\u89AA\u7BC0"
- "holiday_name_\u8FB2\u66C6\u65B0\u5E74"
- "holiday_name_\u897F\u6D0B\u60C5\u4EBA\u7BC0"
- "holiday_name_\u5143\u5BB5\u7BC0"
- "holiday_name_\u52DE\u52D5\u7BC0"
- "holiday_name_\u7236\u89AA\u7BC0"
- "holiday_name_\u5152\u7AE5\u8207\u6E05\u660E\u7BC0"
- "holiday_name_\u570B\u6176\u65E5"
- "holiday_name_\u767D\u8272\u60C5\u4EBA\u7BC0"
- "holiday_name_\u6559\u5E2B\u7BC0"
- "holiday_name_\u4E2D\u5143\u7BC0"
- "holiday_name_\u7AEF\u5348\u7BC0"
- "holiday_name_\u842C\u8056\u7BC0"
- "holiday_name_\u4E03\u5915\u60C5\u4EBA\u7BC0"
- "holiday_name_\u4E2D\u79CB\u7BC0"
h: 672
hidden_size: 256
hist_exog_list:
- ds_prev_1_WATT
- ds_prev_3_WATT
- ds_prev_2_WATT
- ds_prev_4_WATT
- ds_prev_5_WATT
- congestion_syndrome
input_size: 1344
learning_rate: 0.001
loss: !!python/object:neuralforecast.losses.pytorch.RMSE
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: true
lr_scheduler: null
lr_scheduler_kwargs: null
max_steps: 500
n_series: 1
num_layers: 2
num_lr_decays: -1
num_workers_loader: 0
optimizer: null
optimizer_kwargs: null
random_seed: 1
scaler_type: standard
stat_exog_list: null
step_size: 1
val_check_steps: 100
valid_loss: null
